using System.Reflection;
using Terraria;

namespace AlienBloxTools.Utilities
{
    public static class InitialiseUtilities
    {
        /// <summary>
        /// The default location for saving exes
        /// </summary>
        public static readonly string EXESaves = $"{Main.SavePath}\\AlienBloxTools\\Exes";
        /// <summary>
        /// Extracts the tModUnpacker included with AlienBlox's Tools
        /// </summary>
        public static void ExtractTMODUnpacker()
        {
            if (!Directory.Exists(EXESaves))
            {
                Directory.CreateDirectory(EXESaves);
            }

            ExtractExe("AlienBloxTools.Utilities.IncludedExes.tModUnpacker.exe", EXESaves);
        }

        /// <summary>
        /// Quickly extracts an EXE from the library
        /// </summary>
        /// <param name="resourceName">The path of the exe</param>
        /// <param name="outputPath">The area to output to.</param>
        /// <exception cref="Exception">any exceptions generated by the utility</exception>
        public static void ExtractExe(string resourceName, string outputPath)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();

            // Full resource name usually: {DefaultNamespace}.{Folder}.{FileName}
            using Stream resourceStream = assembly.GetManifestResourceStream(resourceName) ?? throw new Exception("Resource not found: " + resourceName);
            using FileStream fileStream = new(outputPath, FileMode.Create, FileAccess.Write);
            resourceStream.CopyTo(fileStream);
        }

        /// <summary>
        /// Extracts a file from an assembly
        /// </summary>
        /// <param name="assembly">The assembly to extract</param>
        /// <param name="contentToExtract">The content to extract</param>
        /// <returns>The filestream of the item</returns>
        /// <exception cref="Exception">The exception thrown.</exception>
        public static Stream ExtractContentFromAssembly(Assembly assembly, string contentToExtract)
        {
            // Full resource name usually: {DefaultNamespace}.{Folder}.{FileName}
            using Stream resourceStream = assembly.GetManifestResourceStream(contentToExtract) ?? throw new Exception("Resource not found: " + contentToExtract);

            return resourceStream;
        }
    }
}