using System.Reflection;
using Terraria;

namespace AlienBloxTools.Utilities
{
    public static class InitialiseUtilities
    {
        /// <summary>
        /// Extracts the tModUnpacker included with AlienBlox's Tools
        /// </summary>
        public static void ExtractTMODUnpacker()
        {
            ExtractExe("AlienBloxTools.Utilities.tModUnpacker.exe", $"{Main.SavePath}\\AlienBloxTools\\Exes");
        }

        /// <summary>
        /// Quickly extracts an EXE from the library
        /// </summary>
        /// <param name="resourceName">The path of the exe</param>
        /// <param name="outputPath">The area to output to.</param>
        /// <exception cref="Exception">any exceptions generated by the utility</exception>
        public static void ExtractExe(string resourceName, string outputPath)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();

            // Full resource name usually: {DefaultNamespace}.{Folder}.{FileName}
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            using Stream resourceStream = assembly.GetManifestResourceStream(resourceName) ?? throw new Exception("Resource not found: " + resourceName);
            using FileStream fileStream = new FileStream(outputPath, FileMode.Create, FileAccess.Write);
            resourceStream.CopyTo(fileStream);
        }
    }
}